### ISSUE TITLE
action not propagated to next response

### ISSUE THREAD

**Issue by rogerz** [HubSpot/general-store#33]
I have two stores defined response to the same action. When the action is triggered, only one response will be called. If I change the called `defineResponseTo()` to a dummy action, the other one is called.

Is this a limitation in `general-store`?

```
var ConfigStore = GeneralStore.define()
  .defineGet(function () {
    return config;
  })
  .defineResponseTo('CONFIG_LOADED', function (data) {
    if (!data.err) {
      config = data.content;
    }
  })
  .register(dispatcher);
```

```
var StatusStore = GeneralStore.define()
  .defineGet(function () {
    return status;
  })
  .defineResponseTo('CONFIG_LOADED', function (data) {
    if (!data.err) {
      status.config = 'ready';
    } else {
      status.config = data.err;
    }
  })
  .register(dispatcher);
```

**Comment by colbyr** [comment]
Hmm, no that's not expected behavior.
The problem you're describing doesn't reproduce in isolation: http://jsbin.com/duhiqa/edit?js,console

It sounds to me like there's an error in one of the `defineResponseTo` callbacks which is causing the dispatch fail before the other response is executed.

Could you post a code snippet with more context? Maybe there's something wrong that isn't entirely obvious from these snippets.

**Comment by rogerz** [comment]
Thank you @colbyr .

I checked my code again and it seems cause by an exception during component rendering.

Now I'm a bit curious why this would halt action dispatching. I though the component rendering is triggered asynchronously.

**Comment by colbyr** [comment]
Glad to help!

Also in React, *afaik* the calls to `render` that construct the component tree for diffing will be synchronous, while the actual DOM mutations are asynchronous.
